# 2026.05.01 :: \ub370\uc774\ud130\ubca0\uc774\uc2a4 \ud504\ub85c\ud37c\ud2f0\ub85c \uc124\uc815\uc73c\ub85c \ubcc0\uacbd
db.driver=oracle.jdbc.driver.OracleDriver
db.url=jdbc:oracle:thin:@127.0.0.1:1521:orcl
db.username=nsys
db.password=manager!